[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028FAEE7CA50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/6a9a9a58f76d114dc796f7c14bf6254c
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028FAEE7D250>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/6a9a9a58f76d114dc796f7c14bf6254c
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028FAEE7D990>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/6a9a9a58f76d114dc796f7c14bf6254c